// Generated by `npm run config` from every src/sites/*/config.ts. Don't edit by hand.

import type { IDirectoryEntry } from './directory-types'

export type { IDirectoryEntry }

export const DIRECTORY: IDirectoryEntry[] = [
  {
    slug: '1-lavishboutique',
    name: 'Lavish Boutique',
    tagline: 'Elegant stitches, perfect fit',
    logo: 'logo.png',
    colors: { primary: '#5B2A6E', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Bridal and designer blouses',
      'Custom fit lehengas & gowns',
      'Aari & maggam hand embroidery',
    ],
    rating: 4.9,
  },
  {
    slug: '10-shantifashionnest',
    name: 'Shanti Fashion Nest',
    tagline: 'Elegant design, exquisite craft',
    logo: 'logo.png',
    colors: { primary: '#1F7A7A', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Handcrafted bridal blouses',
      'Intricate aari & maggam hand embroidery',
      'Custom fit lehengas & anarkalis',
    ],
    rating: 4.7,
  },
  {
    slug: '11-sarikadesigner',
    name: 'Sarika Designer and Boutique',
    tagline: 'Fashion that fits your style and budget',
    logo: 'logo.png',
    colors: { primary: '#7A1F2B', accent: '#C9A24A' },
    places: [
      { state: 'Karnataka', city: 'Bengaluru', area: 'Kengeri', pincode: '560060' },
    ],
    featured: [
      'Custom designer blouses',
      'Budget-friendly ethnic tailoring',
      'Bridal embroidery & alterations',
    ],
    rating: 4.5,
  },
  {
    slug: '12-shukradesigner',
    name: 'Shukra Designer Boutique',
    tagline: 'Elegance in Every Stitch, Perfection in Every Detail',
    logo: 'logo.png',
    colors: { primary: '#6C2C7A', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Vishweshwaraiah Layout',
        pincode: '560056',
      },
    ],
    featured: [
      'Bridal blouse & Aari embroidery',
      'Maggam and computerized embroidery',
      'Custom ethnic wear & flawless fitting',
    ],
    rating: 5,
  },
  {
    slug: '13-jasmineboutique',
    name: 'Jasmine Boutique',
    tagline: '20 Years of Timeless Elegance & Bespoke Tailoring',
    logo: 'logo.png',
    colors: { primary: '#1B4D3E', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      '20 years designer wear & bridal blouse specialist',
      'Precision fit blouses with zero alterations',
      'Custom ethnic wear, lehengas & western gowns',
    ],
    rating: 4.3,
  },
  {
    slug: '14-nineplus',
    name: 'Nine Plus',
    tagline: 'Precision Embroidery & Bespoke Designer Wear',
    logo: 'logo.png',
    colors: { primary: '#1B2A4A', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Computer & multi-head embroidery works',
      'Hand Aari, Maggam & Zardosi bridal blouses',
      'Custom designer lehenga & ethnic wear tailoring',
    ],
    rating: 4.8,
  },
  {
    slug: '15-siricreations',
    name: 'Siri Creations',
    tagline: 'Handcrafted Saree Tassels, Bridal Crochet & Designer Tailoring',
    logo: 'logo.png',
    colors: { primary: '#9F1239', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Handcrafted bridal saree kuchu (tassels)',
      'Saree crochet border artwork & bead detailing',
      'Custom designer blouses & saree pre-pleating',
    ],
    rating: 4.9,
  },
  {
    slug: '16-honeyboutique',
    name: 'Honey Boutique',
    tagline: 'Graceful Designs, Sweet Silhouettes & Perfect Fits',
    logo: 'logo.png',
    colors: { primary: '#D97706', accent: '#7A1F2B' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Nagadevanahalli',
        pincode: '560056',
      },
    ],
    featured: [
      'Custom designer blouse styling & precision cuts',
      'Bridal lehengas & festive ethnic tailoring',
      'Flawless alterations & zero-alteration fitting',
    ],
    rating: 4.8,
  },
  {
    slug: '17-ayaanadesigners',
    name: 'Ayaana Designers',
    tagline: 'By Nayana — Bridal Wear, Rental Couture & Custom Designer Dresses',
    logo: 'logo.png',
    colors: { primary: '#18181B', accent: '#FF2A85' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Bridal wear & wedding lehengas on rent',
      'Custom designer gowns & reception dresses',
      'Bespoke blouse stitching & zari embroidery',
    ],
    rating: 4.5,
  },
  {
    slug: '18-anarghyadesigner',
    name: 'Anarghya Designer Studio',
    tagline: 'Men | Women | Kids Wear — Custom Bridal Wear & Rental Collection',
    logo: 'logo.png',
    colors: { primary: '#3B1F2B', accent: '#E5A93C' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Nagadevanahalli',
        pincode: '560056',
      },
    ],
    featured: [
      'Complete family designer wear (Men, Women & Kids)',
      'Luxury bridal & occasion wear rental collections',
      'Custom bridal lehengas, blouses & Indo-Western gowns',
    ],
    rating: 4.4,
  },
  {
    slug: '19-daarinaboutique',
    name: 'Daarina Boutique',
    tagline: 'Custom Tailoring, Exquisite Embroidery & Designer Clothing',
    logo: 'logo.png',
    colors: { primary: '#722F37', accent: '#C9A24A' },
    places: [
      { state: 'Karnataka', city: 'Bengaluru', area: 'Kodipalya', pincode: '560060' },
    ],
    featured: [
      'Precision fit designer blouses',
      'Custom Aari & Maggam hand embroidery',
      'Everyday salwar suits, kurtis & alterations',
    ],
    rating: 4.7,
  },
  {
    slug: '2-vastravinyasaki',
    name: 'Vastra Vinyasaki Boutique',
    tagline: 'Tailored with grace, worn with elegance',
    logo: 'logo.png',
    colors: { primary: '#D2691E', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Designer bridal blouses',
      'Custom fit lehengas & ethnic gowns',
      'Handcrafted aari and maggam embroidery',
    ],
    rating: 4.7,
  },
  {
    slug: '20-kaladesigner',
    name: 'Kala Designer Boutique',
    tagline: 'The Art of Perfect Fit & Exquisite Embroidery',
    logo: 'logo.png',
    colors: { primary: '#881337', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Nagadevanahalli',
        pincode: '560056',
      },
    ],
    featured: [
      'Handcrafted bridal blouse maggam & zardosi embroidery',
      'Custom designer Anarkalis, lehengas & gowns',
      'Precision blouse fitting with zero alterations',
    ],
    rating: 5,
  },
  {
    slug: '21-dharyadesigner',
    name: 'Dharya Designer Studio',
    tagline: 'Luxury Bridal Couture, Bespoke Ethnic Wear & Designer Rentals',
    logo: 'logo.png',
    colors: { primary: '#0D0D0D', accent: '#C5A059' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Jnana Bharathi',
        pincode: '560056',
      },
    ],
    featured: [
      'Luxury bridal lehengas & couture blouse tailoring',
      'Hand Zardosi, Aari & pearl embroidery',
      'Designer gown & wedding wear rental collection',
    ],
    rating: 4.9,
  },
  {
    slug: '22-vinathicollections',
    name: 'Vinathi Ladies Collections',
    tagline: 'Ladies Collections — Sarees, Kurtis & Custom Boutique Tailoring',
    logo: 'logo.png',
    colors: { primary: '#121212', accent: '#F59E0B' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Jnana Bharathi',
        pincode: '560056',
      },
    ],
    featured: [
      'Silk saree & festive ethnic retail',
      'Custom designer blouse & Aari embroidery tailoring',
      'Readymade designer kurtis & family celebration wear',
    ],
    rating: 4.5,
  },
  {
    slug: '23-lalithaboutique',
    name: 'Lalitha Boutique',
    tagline: 'Hand Work & Machine Embroidering — Chudidar & Blouse Stitching, Langa etc.',
    logo: 'logo.png',
    colors: { primary: '#DC2626', accent: '#F59E0B' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Jnana Bharathi',
        pincode: '560056',
      },
    ],
    featured: [
      'Hand work & machine embroidery',
      'Chudidar & designer blouse precision stitching',
      'Traditional pattu langa & everyday ethnic tailoring',
    ],
    rating: 4.2,
  },
  {
    slug: '24-houseoftaranga',
    name: 'House Of Taranga',
    tagline: 'Contemporary Designer Studio & Bespoke Couture',
    logo: 'logo.png',
    colors: { primary: '#0A0A0A', accent: '#D4AF37' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Jnana Ganga Nagar',
        pincode: '560056',
      },
    ],
    featured: [
      'Contemporary designer blouses & precision fits',
      'Custom Anarkalis, lehengas & party gowns',
      'Aari & Maggam hand embroidery styling',
    ],
    rating: 4.2,
  },
  {
    slug: '25-gboutique',
    name: 'G Boutique',
    tagline: 'Elegant Designer Blouses, Bespoke Ethnic Wear & Flawless Fits',
    logo: 'logo.png',
    colors: { primary: '#0A0A0A', accent: '#D4AF37' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Jnana Ganga Nagar',
        pincode: '560056',
      },
    ],
    featured: [
      'Precision fit designer blouses',
      'Aari, Maggam & bead work embroidery',
      'Custom ethnic partywear & lehengas',
    ],
    rating: 4.8,
  },
  {
    slug: '26-adhruthfashion',
    name: 'Adhruth Fashion',
    tagline: 'The designer boutique — Bespoke Bridal Embroidery & Haute Couture',
    logo: 'logo.png',
    colors: { primary: '#D4AF37', accent: '#DC2626' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Jnana Ganga Nagar',
        pincode: '560056',
      },
    ],
    featured: [
      'Royal Maggam & computerized bridal embroidery',
      'Precision fit designer blouses',
      'Custom ethnic lehengas & family celebration wear',
    ],
    rating: 4.3,
  },
  {
    slug: '27-houseofatelier',
    name: 'House Of Atelier',
    tagline: 'Modern Couture, Bespoke Silhouettes & Haute Fashion',
    logo: 'logo.png',
    colors: { primary: '#FACC15', accent: '#1E293B' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Nagadevanahalli',
        pincode: '560056',
      },
    ],
    featured: [
      'Contemporary Indo-Western couture & gowns',
      'Precision fit designer blouses',
      'Custom ethnic lehengas & bridal embroidery',
    ],
    rating: 4.6,
  },
  {
    slug: '28-petalsdesigner',
    name: 'Petals Designer Studio',
    tagline: 'Exclusive Designer Blouses, Bridal Embroidery & Gown Rentals',
    logo: 'logo.png',
    colors: { primary: '#FACC15', accent: '#18181B' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Nagadevanahalli',
        pincode: '560056',
      },
    ],
    featured: [
      'Designer blouses & precision cut stitching',
      'Hand & machine embroidery with bridal detailing',
      'Rental collection of ready designer gowns & blouses',
    ],
    rating: 4.4,
  },
  {
    slug: '29-vinyasadesigner',
    name: 'Vinyasa Designer Boutique',
    tagline: 'Dreams of Dresses · Modern Couture & Bridal Embroidery',
    logo: 'logo.png',
    colors: { primary: '#DB2777', accent: '#FFFFFF' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Nagadevanahalli',
        pincode: '560056',
      },
    ],
    featured: [
      'Bridal aari and maggam embroidery blouses',
      'Designer kids couture frocks & lehengas',
      'Precision-cut designer blouses with zero alteration guarantee',
    ],
    rating: 5,
  },
  {
    slug: '3-siddhiboutique',
    name: 'Siddhi Boutique',
    tagline: 'Bespoke tailoring, timeless style',
    logo: 'logo.png',
    colors: { primary: '#D8577E', accent: '#C9A24A' },
    places: [
      { state: 'Karnataka', city: 'Bengaluru', area: 'Kodipalya', pincode: '560060' },
    ],
    featured: [
      'Designer bridal blouses',
      'Saree upcycling into designer dresses',
      'Custom fit lehengas & gowns',
    ],
    rating: 4.8,
  },
  {
    slug: '4-shaaridesignerhouse',
    name: 'Shaari Designer House',
    tagline: 'Customisation Available In All Kinds Of Designer Outfits',
    logo: 'logo.png',
    colors: { primary: '#6B2D8E', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Contemporary designer blouses',
      'Custom bridal lehengas & gowns',
      'Intricate aari & zardosi handwork',
    ],
    rating: 4.6,
  },
  {
    slug: '5-zivaboutique',
    name: 'Ziva Boutique',
    tagline: 'Because Your Fit is Personal - Ziva stitches it right!',
    logo: 'logo.png',
    colors: { primary: '#C2185B', accent: '#F2B38F' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Handcrafted designer blouses',
      'Fit-led precision tailoring',
      'Indian fusion & festive wear',
    ],
    rating: 4.5,
  },
  {
    slug: '6-aadhyaboutique',
    name: 'Aadhya Boutique',
    tagline: 'Grace in every drape, beauty in every stitch',
    logo: 'logo.png',
    colors: { primary: '#7A1F2B', accent: '#C9A24A' },
    places: [
      { state: 'Karnataka', city: 'Bengaluru', area: 'Kengeri', pincode: '560060' },
    ],
    featured: [
      'Designer bridal blouses',
      'Aari & maggam hand embroidery',
      'Custom fit lehengas & salwars',
    ],
    rating: 4.4,
  },
  {
    slug: '7-aishwaryafashion',
    name: 'Aishwarya Fashion',
    tagline: 'Everyday fashion, festive grace',
    logo: 'logo.png',
    colors: { primary: '#5B2A6E', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Women\'s readymade ethnic wear',
      'Custom designer blouses',
      'Alterations and quick turnaround tailoring',
    ],
    rating: 4.5,
  },
  {
    slug: '8-jhumkotashvi',
    name: 'Jhumko Tashvi Designer',
    tagline: 'Handcrafted elegance, stitched to perfection',
    logo: 'logo.png',
    colors: { primary: '#5E1A2E', accent: '#C9A24A' },
    places: [
      {
        state: 'Karnataka',
        city: 'Bengaluru',
        area: 'Kengeri Satellite Town',
        pincode: '560060',
      },
    ],
    featured: [
      'Handcrafted designer bridal blouses',
      'Custom fit lehengas & festive gowns',
      'Aari and zardosi hand embroidery',
    ],
    rating: 4.3,
  },
  {
    slug: '9-anantharathna',
    name: 'Anantharathna Boutique',
    tagline: 'Traditional artistry, bespoke perfection',
    logo: 'logo.png',
    colors: { primary: '#7A1F2B', accent: '#C9A24A' },
    places: [
      { state: 'Karnataka', city: 'Bengaluru', area: 'Harsha Layout', pincode: '560060' },
    ],
    featured: [
      'Handcrafted bridal maggam blouses',
      'Custom fit lehengas & anarkalis',
      'Aari & stone work embroidery',
    ],
    rating: 4.7,
  },
  {
    slug: 'sample-boutique',
    name: 'Sample Boutique',
    tagline: 'Stitched to you, thread by thread',
    logo: 'logo.png',
    colors: { primary: '#7A1F2B', accent: '#C9A24A' },
    places: [
      {
        state: 'Andhra Pradesh',
        city: 'Tirupati',
        area: 'Temple Street',
        pincode: '517501',
      },
    ],
    featured: ['Bridal maggam blouses', 'Designer lehengas', 'Pattu pavadai for kids'],
    rating: 4.8,
  },
]
