// scripts/lib/directory.mjs
// Writes src/app/directory-data.ts: one small line per boutique — its name, its
// colours and everywhere it has a branch — for the demo directory's filters.
//
// The directory needs all 500 boutiques at once, and the full configs are far
// too much to load for a list. So this pulls out only what the list and the
// filters read, into a single file the page can import outright.

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { allSlugs, root, siteDir } from './paths.mjs'
import { toTs } from './data-sheet.mjs'

const OUT = join(root, 'src', 'app', 'directory-data.ts')
const HEADER = '// Generated by `npm run config` from every src/sites/*/config.ts. Don\'t edit by hand.'

/** The one line the directory keeps about a boutique. */
function entry(config) {
  const places = (config.branches ?? []).map((b) => ({
    state: b.state,
    city: b.city,
    area: b.area,
    pincode: b.pincode,
  }))
  return {
    slug: config.slug,
    name: config.brand?.name ?? config.slug,
    tagline: config.brand?.tagline,
    logo: config.brand?.logo,
    colors: { primary: config.brand?.colors?.primary, accent: config.brand?.colors?.accent },
    places,
    featured: (config.services?.featured ?? []).slice(0, 3),
    rating: config.social?.googleRating,
  }
}

/** Every boutique that has a generated config, in folder order. */
export async function readEntries() {
  const entries = []
  for (const slug of allSlugs()) {
    const path = join(siteDir(slug), 'config.ts')
    if (!existsSync(path)) continue
    try {
      const config = (await import(`${pathToFileURL(path).href}?t=${Date.now()}`)).default
      entries.push(entry(config))
    } catch {
      // A config that can't be read is already an error from the validator.
    }
  }
  return entries
}

export async function writeDirectory() {
  const entries = await readEntries()
  const source = `${HEADER}

import type { IDirectoryEntry } from './directory-types'

export type { IDirectoryEntry }

export const DIRECTORY: IDirectoryEntry[] = ${toTs(entries)}
`
  writeFileSync(OUT, source)
  return entries.length
}

/** Slugs the written directory holds, for checking it hasn't gone stale. */
export function listedSlugs() {
  if (!existsSync(OUT)) return null
  return [...readFileSync(OUT, 'utf8').matchAll(/^    slug: '([^']+)',$/gm)].map((m) => m[1])
}
